### ISSUE TITLE
KeyError in 'beangrow/reports.py', line 459

### ISSUE THREAD

**Issue by ThomasdenH** [beancount/beangrow#5]
I get the following error:
```
Traceback (most recent call last):
  File "../Git/beangrow/beangrow/compute_returns.py", line 105, in <module>
    main()
  File "../Git/beangrow/beangrow/compute_returns.py", line 86, in main
    pricer = reports.generate_reports(account_data_map, config,
  File "/mnt/f/Git/beangrow/beangrow/reports.py", line 459, in generate_reports
    adlist = [account_data_map[name] for name in report.investment]
  File "/mnt/f/Git/beangrow/beangrow/reports.py", line 459, in <listcomp>
    adlist = [account_data_map[name] for name in report.investment]
KeyError: 'ACCOUNT_NAME'
```
I can't exclude the possibility that this is something wrong with my configuration. I am happy to share the config file and my `.beancount` files in private.

**Comment by floatingheads** [comment]
@ThomasdenH do you have prices defined for the commodity? I feel like I came across that error when I was getting this configured. If it's not that, I'm happy to take a look at your files.
